# -*- coding: utf-8 -*-
"""
鸿蒙小雨核心模块
提供依赖注入、事件总线、错误处理、突触总线、统一枚举等基础设施

优化：延迟导入，避免一次性加载所有核心模块导致初始化卡顿
"""

import importlib

_LAZY_MODULES = {
    'SynapticBus': '.synaptic_bus',
    'SynapticMessage': '.synaptic_bus',
    'DeliveryReceipt': '.synaptic_bus',
    'RouteRule': '.synaptic_bus',
    'synaptic_bus': '.synaptic_bus',
    'get_synaptic_bus': '.synaptic_bus',
    'DualLoopEngine': '.dual_loop_engine',
    'InnerLoopCoordinator': '.dual_loop_engine',
    'OuterLoopCoordinator': '.dual_loop_engine',
    'LoopPhase': '.dual_loop_engine',
    'InnerLoopStage': '.dual_loop_engine',
    'OuterLoopStage': '.dual_loop_engine',
    'LoopMetrics': '.dual_loop_engine',
    'LoopState': '.dual_loop_engine',
    'get_dual_loop_engine': '.dual_loop_engine',
    'UnifiedStorage': '.unified_storage',
    'StorageTier': '.unified_storage',
    'EvictionPolicy': '.unified_storage',
    'MemoryCategory': '.unified_storage',
    'StorageItem': '.unified_storage',
    'CacheLayer': '.unified_storage',
    'RelationalLayer': '.unified_storage',
    'VectorLayer': '.unified_storage',
    'FileLayer': '.unified_storage',
    'get_unified_storage': '.unified_storage',
    'CompoundInterestEngine': '.compound_engine',
    'CompoundPhase': '.compound_engine',
    'AssetType': '.compound_engine',
    'AssetStatus': '.compound_engine',
    'KnowledgeAsset': '.compound_engine',
    'IngestPipeline': '.compound_engine',
    'DigestPipeline': '.compound_engine',
    'OutputPipeline': '.compound_engine',
    'IteratePipeline': '.compound_engine',
    'get_compound_engine': '.compound_engine',
    'DualLoopCompoundEngine': '.dual_loop_compound',
    'InnerCompoundCycle': '.dual_loop_compound',
    'OuterCompoundCycle': '.dual_loop_compound',
    'CompoundScope': '.dual_loop_compound',
    'CompoundCycleResult': '.dual_loop_compound',
    'get_dual_loop_compound': '.dual_loop_compound',
    'InteractionCompoundCycle': '.interaction_compound',
    'InteractionType': '.interaction_compound',
    'SatisfactionLevel': '.interaction_compound',
    'SkillGapSource': '.interaction_compound',
    'InteractionRecord': '.interaction_compound',
    'get_interaction_compound': '.interaction_compound',
    'LLMWikiCompatLayer': '.llm_wiki_compat',
    'WikiSourceType': '.llm_wiki_compat',
    'ChunkStrategy': '.llm_wiki_compat',
    'WikiDocument': '.llm_wiki_compat',
    'SearchResult': '.llm_wiki_compat',
    'DocumentChunker': '.llm_wiki_compat',
    'get_llm_wiki_compat': '.llm_wiki_compat',
    'DependencyContainer': '.container',
    'ServiceLifetime': '.container',
    'ServiceDescriptor': '.container',
    'ServiceLocator': '.container',
    'injectable': '.container',
    'inject': '.container',
    'container': '.container',
    'get_container': '.container',
    'configure_services': '.container',
    'EventBus': '.event_bus',
    'Event': '.event_bus',
    'Subscription': '.event_bus',
    'event_bus': '.event_bus',
    'get_event_bus': '.event_bus',
    'on_event': '.event_bus',
    'ErrorHandler': '.error_handler',
    'ErrorContext': '.error_handler',
    'RetryConfig': '.error_handler',
    'HMYXException': '.error_handler',
    'ToolExecutionError': '.error_handler',
    'LLMError': '.error_handler',
    'ValidationError': '.error_handler',
    'TimeoutError': '.error_handler',
    'retry': '.error_handler',
    'safe_execute': '.error_handler',
    'error_handler': '.error_handler',
    'get_error_handler': '.error_handler',
    'HeartStatus': '.enums',
    'ServiceStatus': '.enums',
    'LoopStatus': '.enums',
    'WorkflowStatus': '.enums',
    'SessionState': '.enums',
    'FlowStatus': '.enums',
    'CommandStatus': '.enums',
    'ToolStatus': '.enums',
    'ChangeStatus': '.enums',
    'AlertLevel': '.enums',
    'TaskPriority': '.enums',
    'ContextPriority': '.enums',
    'EventPriority': '.enums',
    'IssueSeverity': '.enums',
    'ErrorSeverity': '.enums',
    'ViolationSeverity': '.enums',
    'RiskLevel': '.enums',
    'NudgePriority': '.enums',
    'ErrorCategory': '.enums',
    'RecoveryStrategy': '.enums',
    'VerificationStatus': '.enums',
    'MemoryType': '.enums',
    'MemoryPriority': '.enums',
    'MemoryStatus': '.enums',
    'SkillCategory': '.enums',
    'SkillStatus': '.enums',
    'SkillLevel': '.enums',
    'SecurityLevel': '.enums',
    'ExecutionMode': '.enums',
    'TaskComplexity': '.enums',
    'TaskType': '.enums',
    'TaskStatus': '.enums',
    'CognitiveLayerType': '.enums',
    'FeedbackType': '.enums',
    'CausalRelationType': '.enums',
    'NodeType': '.enums',
    'PhysicalLawType': '.enums',
    'ConfounderType': '.enums',
    'ContextType': '.enums',
    'EmotionalState': '.enums',
    'CognitiveLoadLevel': '.enums',
    'EngagementLevel': '.enums',
    'ContentType': '.enums',
    'AttentionType': '.enums',
    'EvolutionPhase': '.enums',
    'AdaptationType': '.enums',
    'KnowledgeType': '.enums',
    'DistillationPhase': '.enums',
    'KnowledgeStatus': '.enums',
    'LearningStage': '.enums',
    'LearningStatus': '.enums',
    'LearningPhase': '.enums',
    'ImprovementType': '.enums',
    'SkillContext': '.enums',
    'KairosMode': '.enums',
    'KairosStrategy': '.enums',
    'KairosMemoryType': '.enums',
    'KairosUrgency': '.enums',
    'ToolCategory': '.enums',
    'PlatformType': '.enums',
    'GitOperation': '.enums',
    'BranchType': '.enums',
    'ChangeType': '.enums',
    'NeuronType': '.enums',
    'SynapseType': '.enums',
    'PlasticityType': '.enums',
    'NudgeType': '.enums',
    'NudgeStatus': '.enums',
    'SkillEvolutionStage': '.enums',
    'ExperienceType': '.enums',
    'SkillSource': '.enums',
    'SkillExecutionMode': '.enums',
    'SkillActivationType': '.enums',
    'CacheStrategy': '.enums',
    'RegistrySource': '.enums',
    'CommandCategory': '.enums',
    'ServiceLifetimeEnum': '.enums',
    'EventType': '.enums',
    'FlowPhase': '.enums',
    'HistoryAction': '.enums',
    'TestType': '.enums',
    'TestFramework': '.enums',
    'AgentType': '.enums',
    'AgentState': '.enums',
    'MessagePriority': '.enums',
    'RoutingStrategy': '.enums',
    'DeliveryStatus': '.enums',
    'UnifiedSkillDefinition': '.skill_reducer',
    'SkillActivation': '.skill_reducer',
    'DisclosureLevel': '.skill_reducer',
    'SkillCache': '.skill_reducer',
    'SkillDependencyResolver': '.skill_reducer',
    'RouteOptimizer': '.skill_reducer',
    'BodyRestructurer': '.skill_reducer',
    'UnifiedSkillSystem': '.skill_reducer',
    'get_unified_skill_system': '.skill_reducer',
    'AdversarialDeltaDebugger': '.skill_reducer',
    'TokenEstimator': '.skill_reducer',
}

_MODULE_CACHE = {}


def __getattr__(name):
    if name in _LAZY_MODULES:
        module_path = _LAZY_MODULES[name]
        if module_path not in _MODULE_CACHE:
            _MODULE_CACHE[module_path] = importlib.import_module(module_path, __name__)
        module = _MODULE_CACHE[module_path]
        if hasattr(module, name):
            return getattr(module, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    return list(_LAZY_MODULES.keys())


__all__ = list(_LAZY_MODULES.keys())
